server:
  port: 8080
spring:
  application:
    name: "AuthenticationMS"
  devtools:
    add-properties: false
  webflux:
    validator:
      enabled: true
  h2:
    console:
      enabled: true
      path: "/h2"
  profiles:
    include: null
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: "https://idp.example.com/issuer"
          client-id: "myclientid"
jwt:
  json-exp-roles: "/roles"
  secret: MySecretK3y_MySecretK3y_MySecretK3y_MySecretK3y_
  expiration: 86400000
  #expiration: 60000
management:
  endpoints:
    web:
      exposure:
        include: "health,prometheus"
  endpoint:
    health:
      probes:
        enabled: true
cors:
  allowed-origins: "http://localhost:4200,http://localhost:8080"
adapters:
  r2dbc:
    host: ${ADAPTERS_R2DBC_HOST:localhost}
    port: ${ADAPTERS_R2DBC_PORT:5432}
    database: ${ADAPTERS_R2DBC_DATABASE:reto-pragma}
    schema: ${ADAPTERS_R2DBC_SCHEMA:public}
    username: ${ADAPTERS_R2DBC_USERNAME:admin}
    password: ${ADAPTERS_R2DBC_PASSWORD:passwordSQL}
logging:
  level:
    org.springframework.security: DEBUG
  file:
    name: logs/application.log
